services:
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    environment:
      - OTEL_SERVICE_NAME=server
      - OTEL_RESOURCE_ATTRIBUTES
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    environment:
      - OTEL_SERVICE_NAME=client
      - OTEL_RESOURCE_ATTRIBUTES
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - SERVER_URL=http://server:8080
    depends_on:
      - otel-collector

  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.149.0
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM
