AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example lambdas instrumented using different handlers and wrappers

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:

  SplunkLayerNodejsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SplunkLayerNodejsLambdaFunction
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: nodejs14.x
      Timeout: 60
      MemorySize: 256
      Layers:
        - REPLACE_WITH_LAYER_ARN
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/nodejs-otel-handler
          SPLUNK_ACCESS_TOKEN: REPLACE_WITH_SPLUNK_ACCESS_TOKEN
          SPLUNK_REALM: us0
          OTEL_LOG_LEVEL: DEBUG
          OTEL_TRACES_EXPORTER: jaeger-thrift-splunk