extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:    

processors:
  batch:

exporters:
  logging/debug:
    verbosity: detailed
  logging:
    verbosity: normal
  # Traces and metrics
  otlphttp:
     metrics_endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/datapoint/otlp"
     traces_endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace/otlp"
     headers:
        "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"
  # Logs
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/6d0088440deab8be7ff8d7204e73c8a1e36cbbdb/exporter/splunkhecexporter#configuration
  splunk_hec:
    token: "${SPLUNK_HEC_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
# alternatively, logs can be sent directly to splunk o11y cloud
    # token: "${SPLUNK_ACCESS_TOKEN}"
    # endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v1/log"

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - otlphttp
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - otlphttp
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - splunk_hec

  extensions:
    - health_check
    - zpages
